
JOIN_TEXT = 'Привет. Я БОТ-НАПОМИНАЛКА.'
JOIN_TEXT_FOR_USER = 'Привет,{}. Я БОТ-НАПОМИНАЛКА.'

DONKNOW_TEXT='Не понимаю! Повторите ввод!'
NO_COMMENT = 'Нет комментария.'
INVALID_DATE_OR_TIME = 'Не верно введена дата или время! Ошибка: {}. Введите дату напоминания заново.'
ENTER_COMMENT = 'Введите комментарий'
ENTER_MINUTES = 'Введите минуты!'
ENTER_HOURS = 'Введите час!'
ENTER_YEAR = 'Введите год!'
ENTER_MONTH = 'Введите месяц в числовом формате!'
ENTER_DAY = 'Введите день!'
ENTER_DATE = 'Введите дату напоминания!'
COMMIT_WITHOUT_COMMENT = 'Записываю'
COMMIT_WITH_COMMENT = 'Записываю! Дата:{} Комментарий:{} Статус: {}'

ADD_USER = 'Вы в базе!'
ADD_ERROR = 'Ошибка:('
REMOVE_USER = 'Вас больше нет в базе!'
NO_USER = 'Нет такого пользователя:('
ALREADY_EXISTS_USER = '{}, уже есть!'
RUN_BOT = 'Бот запускается'
REMINDER_STATUS_ON_ADD = 'active'

REMINDER_ALL_LIST_MESSAGE = 'Список напоминаний:'
REMINDER_LIST_MESSAGE = 'Дата:{}.Комментарий:{}. Статус {}.'